name: Security
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Security vulnerabilities scan
        uses: actions/aufdenpunkt/python-safety-check

